search/urls.py
from django.urls import path, re_path
from .views import SearchProductView
app_name = 'search'

urlpatterns = [
    path('', SearchProductView.as_view(), name='search_product'),
]

accounts/models.py
#models
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

class Customer(models.Model):
    PAYMENTSTATUS = (
        ('Cleared', 'Cleared'),
    )

    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    invoice_number = models.IntegerField(null=True)
    payment_status = models.CharField(max_length=200, null=True, choices=PAYMENTSTATUS)
    image = models.ImageField(upload_to='allcustomer/', null=True, blank=True)



    def __str__(self):
        return self.name



class Tag(models.Model):
        name = models.CharField(max_length=200, null=True)

        def __str__(self):
            return self.name

class ProductForCustomer(models.Model):
        CATEGORY2 = (
                ('McDonalds', 'McDonalds'),
                ('Jollibee', 'Jollibee'),
                ('Chowking', 'Chowking'),
                ('Coco', 'Coco'),

         )

        name = models.CharField(max_length=200, null=True)
        price = models.FloatField(null=True)
        category = models.CharField(max_length=200, null=True, choices=CATEGORY2)
        description = models.CharField(max_length=200, null=True, blank=True)
        date_created = models.DateTimeField(auto_now_add=True, null=True)
        tags = models.ManyToManyField(Tag)
        image = models.ImageField(upload_to='products/', null=True, blank=True)

        def __str__(self):
                return self.name

class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
    )
    DELIVEREDSTATUS = (
        ('Delivered', 'Delivered'),
    )

    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(ProductForCustomer, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS, blank=True)
    delivered_status = models.CharField(max_length=200, null=True, choices=DELIVEREDSTATUS, blank=True)

    def __str__(self):
        return self.product.name

search/models.py
from django.db import models

# Create your models here.
class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = Q(title_icontains=query) | Q(description_icontains=query) | Q(producttag_title_icontains=query)
        return self.filter(lookups).distinct()

search/views.py
from django.shortcuts import render
from products.models import Product

# Create your views here.
from django.views.generic import ListView

#Search
class SearchProductView(ListView):
    #queryset = Product.objects.all()
    template_name = "search.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(*args, **kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    #Model Manager
    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Product.objects.filter(title__icontains='hat')
        return Product.objects.featured()


# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{% block title %}{% endblock %}</title>
{% load static %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>

    {% block content %}{% endblock %}

<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
       }
    );
} );
</script>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/create_order.html
    {% extends 'main.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body class="test" >


    {% block content %}
    {% comment %}{% include 'base/navbar.html' %} {% endcomment %}
        <!--For Total Price-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <br>

        <form action="" method="POST">
				{% csrf_token %}
				{{form}}

				<input type="submit" name="Submit">
			</form>
    {% comment %}
    <br>

    {% for object in object_list %}
        Title: <a href="{% url 'detailed' object.id %}" >{{ object.title }}</a><br>
    {% endfor %}
    </ul>
    {% endcomment %}

    {% endblock %}

</body>
</html>

templates/createcustomer.html
{% extends 'main.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body class="test" >


    {% block content %}
    {% comment %}{% include 'base/navbar.html' %} {% endcomment %}
        <!--For Total Price-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <br>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="submit">
        </form>
    {% comment %}
    <br>

    {% for object in object_list %}
        Title: <a href="{% url 'detailed' object.id %}" >{{ object.title }}</a><br>
    {% endfor %}
    </ul>
    {% endcomment %}

    {% endblock %}

</body>
</html>

templates/customer2.html
{% extends 'main.html' %}
{% block content %}

<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			{% comment %}<a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a> {% endcomment %}
			<a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'create_order' customer.id %}">Place Order</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email: {{customer.email}}</p>
			<p>Phone: {{customer.phone}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{order_count}}</h1>
		</div>
	</div>
</div>


<br>

<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
                        {{myFilter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>

</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Ordered</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
                {% for order in orders %}

				<tr>
					<td>{{order.product}}</td>
					<td>{{order.date_created}}</td>
					<td>
                            {% if order.status %}
                            {{order.status}}
                                {% elif order.delivered_status %}
                                {{ order.delivered_status }}
                                {% elif order.status == order.delivered_status %}
                                {{ order.status }}
                            {% endif %}



                        </td>

                        {% if order.delivered_status %}
                            <td><a class="btn btn-sm btn-info disabled "href="#">Update</a></td>
                            {% elif order.status %}
                            <td><a class="btn btn-sm btn-info"href="{% url 'update_order' order.id %}">Update</a></td>
                        {% endif %}
						{% if order.delivered_status %}
                        <td><a class="btn btn-sm btn-danger disabled "href="#">Delete</a></td>
                            {% elif order.status %}
                            <td><a class="btn btn-sm btn-danger"href="{% url 'delete_order' order.id %}">Delete</a></td>
                        {% endif %}
				</tr>

                {% endfor %}

			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/dashboard2.html
{% extends 'main.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body>

{% block content %}
    {% include 'status.html' %}


<div class="row">

	<div class="col-md-5">
    <div class="card card-body">

    <h5>CUSTOMERS</h5>
     <br>
     <center>
        <div class="card card-body">
			<form method="get">
                        {{mycusFilter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
    </center>
     <br>
    <hr>
    <div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'createcustomer' %}">Create Customer</a>
			<table class="table table-sm">
				<tr>
                    <th></th>
					<th>Customer</th>
					<th>Phone</th>
				</tr>
                {% for customer in customers %}
                    <tr>
                        <td><a class="btn btn-sm btn-info" href="{% url 'customer' customer.id %}">View</a></td>
                        <td>{{customer.name}}</td>
                        <td>{{customer.phone}}</td>
                    </tr>
                {% endfor %}
			</table>
    </div>
		</div>
	</div>

	<div class="col-md-7">
        <div class="card card-body">
		<h5>LAST 5 ORDERS</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'orderform' %}">Create Order</a>
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
                {% for order in orders %}
                    <tr>
                        <td>{{order.product}}</td>
                        <td>{{order.date_created}}</td>
                        <td>
                            {% if order.status %}
                            {{order.status}}
                                {% elif order.delivered_status %}
                                {{ order.delivered_status }}
                                {% elif order.status == order.delivered_status %}
                                {{ order.status }}
                            {% endif %}



                        </td>

                        {% if order.delivered_status %}
                            <td><a class="btn btn-sm btn-info disabled "href="#">Update</a></td>
                            {% elif order.status %}
                            <td><a class="btn btn-sm btn-info"href="{% url 'update_order' order.id %}">Update</a></td>
                        {% endif %}
						{% if order.delivered_status %}
                        <td><a class="btn btn-sm btn-danger disabled "href="#">Delete</a></td>
                            {% elif order.status %}
                            <td><a class="btn btn-sm btn-danger"href="{% url 'delete_order' order.id %}">Delete</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
			</table>
		</div>
	</div>

</div>

{% endblock %}


</body>
</html>

templates/delete.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'delete_order' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'dashboard' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm">
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/featured-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
    {% include 'base/navbar.html' %}
    <h1>Featured Products</h1>

    {{ object.title }}<br>
    {{ object.description }}<br>
    {% if object.image %}
    <img src="{{ object.image.url }}">
    {% endif %}
</body>
</html>

templates/home.html
<!doctype html>
<html lang="en" >
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->


       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>CloudAnnex</title>



  </head>
  <body>




{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}

       {% block nav %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <img src="{% static 'img/CloudAnnexLogo.png' %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard2' %}">Dashboard</a>
      </li>

        <li class="nav-item">
        <a class="nav-link" href="{% url 'recordlist' %}">Customers</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'products2' %}">Products</a>
      </li>

    </ul>

        {% comment %}
        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'recordlist' %}">Customers</a></li>
        <li><a href="{% url 'products' %}">Products</a></li>
        {% endcomment %}

    <ul class="nav navbar-nav navbar-right list-group-horizontal">
      {% comment %}
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endcomment %}
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out "></span> Logout</a></li>
    </ul>
  </div>

</nav>
  {% endblock %}

<div class="container-fluid">
    <h1>HOMEPAGE</h1>
    <p> Hi {{ user }}!</p>

<!--
    <p><a href="{% url 'dashboard' %}">Dashboard</a></p>
    <p><a href="{% url 'recordlist' %}">Customers</a></p>
    <p><a href="{% url 'products' %}">Products</a></p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
-->



      <div class="form-group">
          <label for="Search"></label>
                <input autocomplete="off" style="width: 250px" type="text" class="form-control" name="Search" id="Search" placeholder="Search">

            </div>
</div>
{% else %}
<section class="vh-100" style="background-color: white;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form>

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Welcome to CloudAnnex!</span>
                  </div>
                    <br>

                      <form autocomplete="off" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                          <a href="{% url 'login' %}" class="btn btn-dark btn-lg btn-block" type="button">Join CloudAnnex</a>
                      </form>

                    <br>
                    <br>
                    <br>

                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account?
                      <a href="{% url 'register' %}"
                      style="color: #393f81;">Sign Up</a></p>
                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endif %}

{% endblock %}

<!-- *No Scripts
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
-->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4></h4>

 <form method="POST" class="post-form" action="/addnew" autocomplete="off">
   {% csrf_token %}
  <div class="container">
 <br>
  <div class="form-group row">
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-4">
  <h3>Enter Details</h3>
  </div>
   </div>

   <div class="form-group row">
  <label class="col-sm-2 col-form-label">Customer Name:</label>
  <div class="col-sm-4">
    <input type="text" name="name" class="form-control" maxlength="100" required id="id_name">
  </div>
   </div>
  <div class="form-group row">
  <label class="col-sm-2 col-form-label">Customer Email:</label>
  <div class="col-sm-4">
    <input type="email" name="email" class="form-control" maxlength="254" required id="id_email">
  </div>
   </div>
  <div class="form-group row">
  <label class="col-sm-2 col-form-label">Customer Contact:</label>
  <div class="col-sm-4">
    <input type="text" name="contact" class="form-control" maxlength="25" required id="id_contact">
  </div>
   </div>
  <div class="form-group row">
  <label class="col-sm-1 col-form-label"></label>
  <div class="col-sm-4">
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
   </div>
  </div>
 </form>
</div>
{% endblock content %}

templates/invoices.html
{% extends 'main.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body class="test" >


    {% block content %}
    {% comment %} {% include 'base/navbar.html' %} {% endcomment %}

        <br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Invoices</h5>
				</div>
            <br>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Invoice No.</th>
							<th>Name</th>
							<th>Date Created</th>
                            <th>Payment Status</th>
						</tr>

                        {% for i in customer2 %}
                            <tr>
                                <td>{{ i.invoice_number }}</td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.date_created }}</td>
                                <td>{{ i.payment_status }}</td>
                            </tr>
                        {% endfor %}
					</table>
				</div>
			</div>

		</div>

    {% comment %}
    <br>

    {% for object in object_list %}
        Title: <a href="{% url 'detailed' object.id %}" >{{ object.title }}</a><br>
    {% endfor %}
    </ul>
    {% endcomment %}

    {% endblock %}

</body>
</html>

templates/list.html
{% extends 'main.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body class="test" >


    {% block content %}
    {% include 'base/navbar.html' %}

        <br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Products</h5>
				</div>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Price</th>
						</tr>

					</table>
				</div>
			</div>

		</div>


    <br>

    {% for object in object_list %}
        Title: <a href="{% url 'detailed' object.id %}" >{{ object.title }}</a><br>
    {% endfor %}
    </ul>


    {% endblock %}

</body>
</html>

templates/products2.html
{% extends 'main.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}

</head>
<body class="test" >


    {% block content %}
    {% comment %}{% include 'base/navbar.html' %} {% endcomment %}
        <!--For Total Price-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function()
        {
            let empiric;
            let totality=0;
            $('td:nth-child(4)').each(function ()
            {
                empiric=$(this).html();
                totality+=parseInt(empiric);
                $('#totalprice').text(totality);
            });
        });
    </script>

        <br>

		<div class="row">

			<div class="col-md">
				<div class="card card-body">
					<h5>Products</h5>
				</div>
            <br>
				<div class="card card-body">
					<table class="table">
						<tr>
                            <th>Image</th>
							<th>Product</th>
							<th>Category</th>
							<th>Price</th>
						</tr>

                        {% for i in products2 %}
                            <tr>
                                <td><center><img class="imgclass" src="{{ i.image.url }}"></center></td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.category }}</td>
                                <td>{{ i.price }}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="3">Total</td>
                            <td id="totalprice"></td>
                        </tr>
					</table>
				</div>
			</div>

		</div>

    {% comment %}
    <br>

    {% for object in object_list %}
        Title: <a href="{% url 'detailed' object.id %}" >{{ object.title }}</a><br>
    {% endfor %}
    </ul>
    {% endcomment %}

    {% endblock %}

</body>
</html>

templates/status.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>